An error occurred: Traceback (most recent call last):
  File "/mnt/c/Users/aimra/Desktop/O-level-PseudoCode-Web-IDE/generatedCode.py", line 2, in <module>
    x = input()
OSError: [Errno 5] Input/output error
